apiVersion: v1
kind: Service
metadata:
  labels:
    app: internal-lb-svc
  name: internal-lb-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    app: internal-deployment
  type: LoadBalancer
status:
  loadBalancer: {}